// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe8azHlHATOyzi_xIhyj9CZAuM6NSSLkk',
    appId: '1:585217764500:web:4094925530b8441bf95881',
    messagingSenderId: '585217764500',
    projectId: 'elitestyle-6dadc',
    authDomain: 'elitestyle-6dadc.firebaseapp.com',
    storageBucket: 'elitestyle-6dadc.firebasestorage.app',
    measurementId: 'G-XFFL2K705V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfvtzCkPtBb8-EWE-caqzhkcxLbGo7jeg',
    appId: '1:585217764500:android:cc1cbfeda90f0da4f95881',
    messagingSenderId: '585217764500',
    projectId: 'elitestyle-6dadc',
    storageBucket: 'elitestyle-6dadc.firebasestorage.app',
  );
}
